name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore ./src/HPHA.UiPath.Core/HPHA.UiPath.Core.csproj

    - name: Build the project
      run: dotnet build --configuration Release --no-restore ./src/HPHA.UiPath.Core/HPHA.UiPath.Core.csproj

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg ./src/HPHA.UiPath.Core/HPHA.UiPath.Core.csproj

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
